name: Release

on:
  push:
    tags:
      - v*

jobs:
  publish:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Package NuGet
      run: |
        dotnet pack --output ./out --configuration Release
        cp ./.github/workflows/nuget.config ./
        dotnet nuget push ./out/*.nupkg -s GitHub --skip-duplicate
        dotnet nuget push ./out/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
